import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const moduleFiles = [
  'app/core/stages.js',
  'app/core/anti-repetition.js',
  'app/core/memory.js',
  'app/core/safety.js',
  'app/core/activities.js',
  'app/core/store.js',
  'app/core/cloud.js',
  'app/core/engine.js',
  'app/app.js',
];

function canonicalImport(fromId, specifier) {
  const joined = path.posix.normalize(path.posix.join(path.posix.dirname(fromId), specifier));
  return joined.startsWith('.') ? joined.slice(2) : joined;
}

function transformModule(id, source) {
  const exports = new Set();
  source = source.replace(/import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"];?/g, (_match, names, specifier) => {
    const resolved = canonicalImport(id, specifier);
    return `const { ${names.trim()} } = __require('${resolved}');`;
  });
  source = source.replace(/export\s+(const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/g, (_match, kind, name) => {
    exports.add(name);
    return `${kind} ${name}`;
  });
  if (/\bexport\s+default\b/.test(source)) throw new Error(`Default export is not supported in ${id}`);
  if (/^\s*(?:import|export)\s/m.test(source.replace(/\/\/.*$/gm, ''))) {
    throw new Error(`Untransformed module syntax remains in ${id}`);
  }
  if (exports.size) source += `\nObject.assign(exports, { ${[...exports].join(', ')} });\n`;
  return source;
}

const html = await readFile(path.join(ROOT, 'app/index.html'), 'utf8');
const css = await readFile(path.join(ROOT, 'app/styles.css'), 'utf8');
const config = await readFile(path.join(ROOT, 'app/config.js'), 'utf8');
const moduleEntries = [];
for (const id of moduleFiles) {
  const source = await readFile(path.join(ROOT, id), 'utf8');
  moduleEntries.push(`${JSON.stringify(id)}: function(module, exports, __require){\n${transformModule(id, source)}\n}`);
}
const runtime = `window.__AH_NATIVE_BUNDLE__ = true;\n${config}\nconst __modules={${moduleEntries.join(',\n')}};\nconst __cache={};\nfunction __require(id){if(__cache[id])return __cache[id].exports;const factory=__modules[id];if(!factory)throw new Error('Missing module '+id);const module={exports:{}};__cache[id]=module;factory(module,module.exports,__require);return module.exports;}\n__require('app/app.js');`;

let output = html
  .replace(/<link[^>]+href=["']\.\/styles\.css[^>]*>\s*/i, '')
  .replace(/<script[^>]+src=["']\.\/config\.js[^>]*><\/script>\s*/i, '')
  .replace(/<script[^>]+src=["']\.\/app\.js[^>]*><\/script>\s*/i, '')
  .replace('<title>Almost Human</title>', '<title>Almost Human · The Haven</title>')
  .replace('</head>', `<style>${css}</style></head>`)
  .replace('</body>', `<script>${runtime.replaceAll('</script>', '<\\/script>')}</script></body>`);

await mkdir(path.join(ROOT, 'mobile/assets'), { recursive: true });
await writeFile(path.join(ROOT, 'mobile/assets/almost-human.html'), output, 'utf8');
await mkdir(path.join(ROOT, 'mobile/src'), { recursive: true });
await writeFile(path.join(ROOT, 'mobile/src/almostHumanHtml.ts'), `// Generated by scripts/build-inline.mjs. Do not edit by hand.\nexport const ALMOST_HUMAN_HTML = ${JSON.stringify(output)} as const;\n`, 'utf8');
await writeFile(path.join(ROOT, 'dist/almost-human-inline.html'), output, 'utf8');
console.log(`Built inline native bundle: ${Buffer.byteLength(output)} bytes`);
